spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: alex
    url: jdbc:mysql://localhost:3306/db_pawn?characterEncoding=utf8&serverTimezone=UTC
  redis:
    port: 6379
    host: localhost
server:
  port: 9999