server:
  port: 8888
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_pawn?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

